name: Release (Main)

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          ref: main
          token: ${{ secrets.REPO_TOKEN }}
          fetch-depth: 0

      - name: Set up Git
        run: git config --global user.name "GitHub Actions" && git config --global user.email "actions@github.com"

      - name: Release
        run: |
            git fetch --all
            git checkout develop
            version=$(awk -F: '/"version"/{gsub(/[",]/, "", $2); print $2}' package.json)
            git checkout main
            git merge origin/develop -m "$version" --no-ff
            git push
            git tag -a $version -m "$version"
            git push origin $version
